name: "ESP-IDF build examples to github pages (push)"

on:
    push:
        branches:
        - master

jobs:

  build:
    strategy:
      matrix:
        include:
          - idf_ver: "v5.1.1"
            parallel_count: 5
            parallel_index: 1
    runs-on: ubuntu-latest
    container: espressif/idf:${{ matrix.idf_ver }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        # with:
        #   submodules: 'recursive'
      - name: Build examples
        shell: bash
        run: |
          export IDF_EXTRA_ACTIONS_PATH=${GITHUB_WORKSPACE}/esp32-s3-lcd-ev-board/examples
          . ${IDF_PATH}/export.sh
          pip install idf-component-manager ruamel.yaml idf-build-apps --upgrade
          echo "Building examples..."
          pwd
          idf-build-apps find
          idf-build-apps build --collect-app-info out.json --build-dir "build_@w" --parallel-count ${{ matrix.parallel_count }} --parallel-index ${{ matrix.parallel_index }}
          echo "Merging binaries and generating config.toml..."
          python ${GITHUB_WORKSPACE}/tools/launchpad/generateFiles.py out.json
          echo "Done building examples."

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: built_files
          path: binaries/

  deploy:
    needs: build

    permissions:
      pages: write      
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Download built files
        uses: actions/download-artifact@v3
        with:
          name: built_files
          path: binaries/

      - name: Upload built files to gh pages
        uses: actions/upload-pages-artifact@v2
        with:
          path: binaries/

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
