.build_template: &build_template
  stage: build
  tags:
    - build
  image: ${IMAGE}
  variables:
    # Enable ccache for all build jobs. See configure_ci_environment.sh for more ccache related settings.
    IDF_CCACHE_ENABLE: "1"
    BATCH_BUILD: "1"
    V: "0"
    WARNING_STR: ""

# Used to skip the unreasonable build job, need be last in the extends list
.build_skip: &build_skip
  rules:
    - when: never

.build_examples_template: &build_examples_template
  <<: *build_template
  artifacts:
    when: always
    paths:
      - "**/build*/size.json"
      - "**/build*/build_log.txt"
      - "**/build*/*.bin"
      # upload to s3 server to save the artifacts size
      - "**/build*/*.map"
      - "**/build*/*.elf"
      - "**/build*/flasher_args.json"
      - "**/build*/flash_project_args"
      - "**/build*/config/sdkconfig.json"
      - "**/build*/bootloader/*.bin"
      - "**/build*/bootloader/*.elf"
      - "**/build*/partition_table/*.bin"
      - size_info.txt
    expire_in: 1 week
  variables:
    IDF_CI_BUILD: "1"
  script:
    - pip install --upgrade idf-component-manager
    - pip install idf_build_apps
    - python tools/build_apps.py ${EXAMPLE_DIR} -t ${EXAMPLE_TARGET} -vv

build_esp32_c3_lcdkit:
  extends:
    - .build_examples_template
    - .rules:build:esp32_c3_lcdkit
  parallel:
    matrix:
      - EXAMPLE_DIR: esp32-c3-lcdkit/examples/knob_panel
  variables:
    EXAMPLE_TARGET: esp32c3
    IMAGE: espressif/idf:release-v5.1

build_esp32_s2_hmi_devkit_1:
  extends:
    - .build_examples_template
    - .rules:build:esp32_s2_hmi_devkit_1
    - .build_skip
  parallel:
    matrix:
      - EXAMPLE_DIR: esp32-s2-hmi-devkit-1/examples/audio/audio_record
      - EXAMPLE_DIR: esp32-s2-hmi-devkit-1/examples/audio/music_player
      - EXAMPLE_DIR: esp32-s2-hmi-devkit-1/examples/freetype
      - EXAMPLE_DIR: esp32-s2-hmi-devkit-1/examples/get-started/hello_world
      - EXAMPLE_DIR: esp32-s2-hmi-devkit-1/examples/get-started/led_blink
      - EXAMPLE_DIR: esp32-s2-hmi-devkit-1/examples/get-started/provision
      - EXAMPLE_DIR: esp32-s2-hmi-devkit-1/examples/power
      - EXAMPLE_DIR: esp32-s2-hmi-devkit-1/examples/sensors
      - EXAMPLE_DIR: esp32-s2-hmi-devkit-1/examples/smart-panel
      - EXAMPLE_DIR: esp32-s2-hmi-devkit-1/examples/storage/sdcard_fatfs
      - EXAMPLE_DIR: esp32-s2-hmi-devkit-1/examples/storage/usb_msc
  variables:
    EXAMPLE_TARGET: esp32s2
    IMAGE: espressif/idf:release-v4.3

build_esp32_s2_kaluga_1:
  extends:
    - .build_examples_template
    - .rules:build:esp32_s2_kaluga_1
  parallel:
    matrix:
      - EXAMPLE_DIR: esp32-s2-kaluga-1/examples/adc_button
      - EXAMPLE_DIR: esp32-s2-kaluga-1/examples/camera
      - EXAMPLE_DIR: esp32-s2-kaluga-1/examples/lcd
      - EXAMPLE_DIR: esp32-s2-kaluga-1/examples/touch
      - EXAMPLE_DIR: esp32-s2-kaluga-1/examples/touch_audio
      - EXAMPLE_DIR: esp32-s2-kaluga-1/examples/web_tts
  variables:
    EXAMPLE_TARGET: esp32s2
    IMAGE: espressif/idf:release-v4.3

build_esp32_s2_touch_devkit_1:
  extends:
    - .build_examples_template
    - .rules:build:esp32_s2_touch_devkit_1
    - .build_skip
  parallel:
    matrix:
      - EXAMPLE_DIR: esp32-s2-touch-devkit-1
  variables:
    EXAMPLE_TARGET: esp32s2
    IMAGE: espressif/idf:release-v4.3

build_esp32_s3_lcd_ev_board:
  extends:
    - .build_examples_template
    - .rules:build:esp32_s3_lcd_ev_board
  parallel:
    matrix:
      - EXAMPLE_DIR: esp32-s3-lcd-ev-board/examples/86box_demo
        IMAGE: espressif/idf:release-v5.1
      - EXAMPLE_DIR: esp32-s3-lcd-ev-board/examples/86box_smart_panel
        IMAGE: espressif/idf:release-v5.1
      - EXAMPLE_DIR: esp32-s3-lcd-ev-board/examples/lvgl_demos
        IMAGE: espressif/idf:release-v5.1
      - EXAMPLE_DIR: esp32-s3-lcd-ev-board/examples/smart_panel
        IMAGE: espressif/idf:release-v5.1
      - EXAMPLE_DIR: esp32-s3-lcd-ev-board/examples/usb_camera_lcd
        IMAGE: espressif/idf:release-v5.1
      - EXAMPLE_DIR: esp32-s3-lcd-ev-board/examples/usb_keyboard
        IMAGE: espressif/idf:release-v5.1
      - EXAMPLE_DIR: esp32-s3-lcd-ev-board/examples/usb_msc_file_sys
        IMAGE: espressif/idf:release-v5.1
  variables:
    EXAMPLE_TARGET: esp32s3

build_esp32_s3_usb_bridge:
  extends:
    - .build_examples_template
    - .rules:build:esp32_s3_usb_bridge
  variables:
    IMAGE: espressif/idf:release-v5.0
    EXAMPLE_TARGET: esp32s2,esp32s3
    EXAMPLE_DIR: esp32-s3-usb-bridge/examples/usb_wireless_bridge

build_esp32_s3_usb_otg:
  extends:
    - .build_examples_template
    - .rules:build:esp32_s3_usb_otg
  parallel:
    matrix:
      - EXAMPLE_DIR: esp32-s3-usb-otg/examples/factory
  variables:
    EXAMPLE_TARGET: esp32s3
    IMAGE: espressif/idf:release-v4.4